### ISSUE TITLE
extract to '@providesModule' to a plugin and maybe open source it ? 

### ISSUE THREAD

**Issue by mitermayer** [facebook/fbjs#154]
I really like the '@providesModule' functionality that has been used all over facebook open source projects, I really find it super useful. was wondering how much work would be involved in extracting it out from here in its own project and open source it ? :D

**Comment by mitermayer** [comment]
just found it on https://github.com/facebook/commoner

**Comment by spicyj** [comment]
commoner is an older project which I'm not sure we use at all any more. Right now I believe we have three open source solutions for handling these:

1. fbjs rewrite-requires is intended to be used with copying all built files to a flat dir and requiring `./X` instead of `X`. We use this for building projects like react and draft-js for npm.
2. The RN packager supports `@providesModule` natively but isn't designed to be general purpose.
3. jest-haste-map (part of jest) can shim the `require` function in node to implement this behavior at runtime. Despite its name, this can be used outside of jest and is not tied to testing.

We don't support any of these for external users though. We might even change our OSS projects to not use `@providesModule` at all over time since it's always an interop hassle.

**Comment by mitermayer** [comment]
Thanks for the answer! I have to admit I like the idea of flatting modules somehow since dealing with '../../' on imports is very painful

**Comment by vko-online** [comment]
+1 Up
