### ISSUE TITLE
React prop-types

### ISSUE THREAD

**Issue by cell2749** [facebook/fbjs#233]
React made some changes regarding prop-types and class creation.
Console gives `"Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead."`

I understand that the updates are relatively new and fbjs team has not yet had time to update the module. I just wanted to bring this up for attention.

**Comment by zpao** [comment]
`fbjs` doesn't use React so should not be triggering that warning itself. Can you paste a full stack trace which is leading you to look here.

**Comment by cell2749** [comment]
The only thing I can see in console is that warning originates from node_modules\fbjs\lib\warning.js:36 
I assume the issue can be closed as it is not fbjs related problem, since as I understood the React modules use the fbjs to print out the warnings. However, for some reason my console does not print out full stack trace and therefore I can't find the root of the problem. (Electron/Chromium)

**Comment by zpao** [comment]
Ok, that's what I suspected was the case - fbjs is just in the stack because React is using the warning module here.

We actually use `console.error` explicitly so that cases like this can log full traces (might need to click to expand). But you can also use the Chrome debugger and pause on caught exceptions as well - we throw and catch and error so that you can do this.

I'm going to close out since it's not actually a bug. If you need more assistance with debugging this sort of thing, please followup with the React folks as they are going to be the most responsive and have the most up to date knowledge on debugging this warning.

**Comment by digitalmaster** [comment]
I'm also getting this same error in RN when running my unit test.. I've already migrated all my src code to the new `prop-types` package so really not sure where this is coming from.

![image](https://user-images.githubusercontent.com/1279335/27716646-a1c0859c-5cf4-11e7-8c30-7cc54de5f718.png)

**Comment by kotazi** [comment]
Same one
![image](https://user-images.githubusercontent.com/4930729/31304491-130f519a-ab5d-11e7-8798-d3f8ab155d24.png)
