### ISSUE TITLE
Doesn't work with flow 0.17.0

### ISSUE THREAD

**Issue by meteficha** [facebook/fbjs#67]
I can't make `fbjs-0.3.1` work with `flow-0.17.0`.  Is it something wrong on my end?

Error messages: https://gist.github.com/meteficha/29bdec5a6ff168fabfa4

**Comment by gregwebs** [comment]
I saw the same issue when upgrading, but it mysteriously went away after reinstalling all my node_modules/

**Comment by zpao** [comment]
I can't repro - could have just been some caching issue. Thanks for reporting but I'm going to close out.

**Comment by meteficha** [comment]
@zpao Assuming it's a cache issue, what should I `rm`?  I've tried `rm -R node_modules` to no avail.  Is there another cache somewhere?

**Comment by gregwebs** [comment]
@zpao can we start a mail list for flow, or can the website specifically suggest using stackoverflow?

These are good ways to leverage the community of users to provide support.

**Comment by zpao** [comment]
If you're running as `flow check src` (from the root of the repo) you can try `flow stop src` which should kill the server that's running there. I'm not super well versed with the other ways Flow does caching so that might not do it.

@gregwebs That's a good idea. I know there's the IRC channel and there was likely a channel in the Reactiflux Slack (though I think that's "full").

**Comment by izaakschroeder** [comment]
Having the exact same issue as @meteficha here. Tried rebuilding `node_modules`, tried killing all instances of `flow`, no luck still :frowning: 

```
node-4.1.0
npm-3.3.5
fbjs-0.3.2
```

**Comment by gregwebs** [comment]
Ignoring fbjs fixed it for us

```
[ignore]
.*/react/node_modules/.*
.*/fbjs
.*/envify
```

**Comment by izaakschroeder** [comment]
Seems like a bit of a hack but it does work! Thanks @gregwebs :smile:
